monarch-initiative/monarch-ui

src/components/MonarchAutocomplete.vue
src/views/Home.vue

Fix search 1

---

src/components/MonarchAutocomplete.vue

Changes phenotype to Phenotype for autocomplete, fixes #4

update phenotype casing

---

src/views/Search.vue

Fix search pagination 9

---

package.json
src/components/GenomeFeature.vue

This cleaned up some irregularities.

cleans up the genome feature view

---

package-lock.json
package.json
src/api/BioLink.js
src/api/MyGene.js
src/components/AssocTable.vue
src/components/ExacGeneSummary.vue
src/components/LocalNav.vue
src/components/NodeCard.vue
src/components/NodeSidebar.vue
src/main.js
src/router.js
src/views/Node.vue

- Removes scaffolding code for literature and associations that has been obviated by new/renamed endpoints.
- Adds kludge for phenotype/Phenotype.
- Reduces number of BL calls.
- Parallelizes the BL /prefixes call with /bioentity/node/ calls.
- Detect MyGene errors without crashing page.

0.0.6 - Use Publication. Optimize BL calls. MyGene error detection.

---

package-lock.json
package.json
src/api/BioLink.js
src/components/MonarchAutocomplete.vue
src/components/Navbar.vue
src/main.js
src/views/Node.vue
src/views/Search.vue
tests/e2e/specs/landing.js

- Adds e2e tests for Home Page search.
- Adds Heritability and Clinical Modifiers to Node.vue.
- Adds additional example to About menu to demonstrate Heritability/ClinicalModifiers.

0.0.8 - Heritability/ClinicalModifiers. e2e tests for Home search.

---

src/views/Node.vue

Fix 78 google structured data

---

package-lock.json
package.json
src/components/Navbar.vue
src/components/ReactomeViewer.vue
src/main.js
src/views/Node.vue

0.0.17
- Adds experimental ReactomeViewer.vue component
- Adds Pathway examples to Navbar
- Eliminates variable-height title bar in Node.vue
- Increases margin between the node content and the cards list.

0.0.17 - Visualize Reactome Pathways

---

.eslintrc.js
src/App.vue
src/components/Footer.vue
src/components/MonarchAutocomplete.vue
src/components/Navbar.vue
src/router.js
src/style/variables.scss
src/views/AboutTeam.md
src/views/Home.vue
src/views/Node.vue
src/views/Sources.vue

- Increasing nav bar height slightly, spacing dropdown items, removing readme & contributing nav-items
- cleaning up footer selection + icons formatting
- Formatting files with attribute breaks to enhance readability. 
- Modifying main content drawer padding
- Supporting static pages should have h2 and centered titles.
These are minor edits as far as I see.
#114

Fixing some css, bigger nav-bar slightly, slight adjustments all around

---

src/components/Navbar.vue
src/router.js
src/views/OtherTools.md

> Adding Other Tools Page 
#101

Adding additional tools page

---

src/components/Navbar.vue

@monicacecilia addressing the comments.
#136

updates to the navbar

---

src/components/Navbar.vue

updating navbar item

---

src/components/AssocTable.vue
src/lib/TaxonMap.js

#94 
Adding species to ortholog tables with links to ncbi taxonomy.

Adding species to ortholog tables

---

src/api/BioLink.js
src/components/Navbar.vue

#143 
simple banner on all pages but the homepage.
If we want it on the homepage easy add, not sure if it makes sense.

adding banner and popover

---

src/components/AssocTable.vue

fixing the homolog to have object instead of subject.
#94

Fixing homolog species identifier

---

src/components/Navbar.vue
src/router.js
src/views/Publications.md

#170 
https://iimpulse.github.io/monarch-ui/about/publications

making titles stand out more, fixing link

---

src/components/Navbar.vue

fixing size of navbarsearch

---

src/components/Navbar.vue

fixing cite link

---

src/components/home/HomePartners.md

Adding EBI logo to replace Sanger logo

Update homepage logos

---

src/views/glossary.md

Adding glossary quickfix

---

package-lock.json
src/api/BioLink.js
src/views/Node.vue

Forwards pages to the ID that is provided by biolink (presumably the clique leader).  This breaks the nextTick() block of code that adjusts the title font size.
This update does not add a message that the user was forwarded from another page, still figuring out how to achieve this.
See also
https://github.com/vuejs/vue-router/issues/1822
https://github.com/vuejs/vue-router/issues/703
https://router.vuejs.org/guide/advanced/navigation-guards.html

Forward pages to clique leader

---

src/api/BioLink.js

Update beta to use api production while I make some breaking changes to dev

Update beta to use api prod

---

src/views/OtherTools.md

Updated Exomiser blurb, and added LIRICAL blurb. @monicacecilia 
@pnrobinson in the Phenix and ExomeWalker sections of this page, the links to Charite pages are all broken. Are there new links at Jax somewhere for these?

Updated Other Tools page

---

src/api/Sources.js
src/views/Sources.vue

Remove redundant 'sources' key causing blank data-sources page

Fix https://beta.monarchinitiative.org/about/data-sources page (currently blank)

---

src/views/Node.vue

reordering sidebar

---

src/components/Navbar.vue

adding main site link

---

src/components/AssocTable.vue
src/components/EvidenceViewer.vue
src/views/Search.vue

Looks like some stuff did change on bootstrap vue tables with the major release into stable

Fixing up bootstrap tables from bump

---

src/views/OtherTools.md

and removed dead PhenIX and ExomeWalker links from other tools, per Peter's request (#280)
To address #280 and #279 (partly)

added a HIPPO section and some updates to ExomeWalker/PhenIX blurbs in OtherTools

---

src/components/AssocTable.vue

moving relation position

---

src/views/OtherTools.md

Added blurbs for Phenogrid, Dipper, HPO Case Annotator, and BOOM, have a look [here](https://justaddcoffee.github.io/monarch-ui/tools/other-tools). 
@iimpulse let me know if you have a better link for phenogrid
@cmungall I pieced together a brief summary for BOOM/kBOOM, feel free to change

Added all the things to Other Tools page

---

src/views/Contact.md

Updating details about mailing lists, clean up details on the page.

Updating the 'Contact Us' page

---

src/components/home/HomePartners.md

removing charite, adding ada

---

src/components/PhenotypesTable.vue

@kshefchek can you test the filter before merging this. think were all set.

fixing my mistakes

---

package.json
src/api/BioLink.js
src/main.js

Adds support for google analytics tracking.  Sets anonymize-ip to true for GDPR compliance.

add google analytics tracking

---

src/views/OtherTools.md

replace http://monarch-exomiser-web-dev.monarchinitiative.org/exomiser with https://exomiser.monarchinitiative.org/exomiser

update exomiser url

---

src/views/OtherTools.md

remove hippo from other tools

---

src/api/MyGene.js

mygene.info requires one fewer backslash for MGI ids

fix MGI mygene call

---

src/api/BioLink.js
src/components/TaxonFilter.vue

Fix taxon filter

---

src/components/Navbar.vue
src/router.js
src/views/AboutPhenotypes.md

Creates an About Phenotypes page as per [Issue 348](https://github.com/monarch-initiative/monarch-ui/issues/348)

Adds an About Phenotypes page

---

src/views/AboutMonarch.md

fix more about hpo link

---

src/api/BBOPGraphUtil.js
src/api/BioLink.js
src/api/News.js
src/api/StaticSourceData.js
src/components/home/HomePartners.md
src/views/Sources.vue

- Fixes javascript Date bug on safari browsers, oregonstate link (thanks @DoctorBud !)
- Fixes source page missing dates and ingest files
closes #355
closes #362

fix home page, sources bugs

---

src/views/Search.vue

addresses #381; removes table striping and adds card and card header styling

adjusts styles on search results table

---

public/team.yaml

@nlharris you inspired me to review my own bio. :)
We'll need to update the OSU and OHSU affiliations when we all move over to CU.

update name of Mondo

---

public/team.yaml

two of the photos of Jackson Lab people are broken.
not sure if the absolute URL will work for sierra's photo.

updated LBNL team members & bios

---

src/App.vue
src/components/DiseaseCarousel.vue
src/components/Footer.vue
src/components/Navbar.vue
src/components/NodeCard.vue
src/components/home/HomePartners.md

Minor css fixes. Larger changes are being contemplated for this week.

Make some css fixes

---

src/views/Disclaimer.md

Here is my paragraph on Hotjar. I am not a lawyer, so perhaps I am not the right one to write this. But I believe this may explain how we use Hotjar in satisfactory detail, and defer to the Hotjar documentation for further details.

Include paragraph on disclaimer page about hotjar

---

public/team.yaml

Adding profile text for team page as requested in Monach onboarding doc. Apologies for creating two different PRs!

Add Harry profile 

---

src/components/home/HomeNews.md

remove twitter feed from homepage

---

src/App.vue
src/components/Banner.vue

This might fail to build after merge due to old node version and sass conflicts. Will be ready to troubleshoot if that happens. Looks like Netlify is not giving us a deploy preview for some reason.

add banner pointing to new site
