- package.json
- public/team.yaml
- publish.sh
- src/NOP.js
- src/api/Team.js
- src/main.js
- src/views/AboutTeam.md
- vue.config.js
- Use / as default for publicPath, unless overridden by BUILD=nonrootdomain, which will use /monarch-ui/ for publicPath.
- Eliminate use of npx, which was overkill.
- Adds 'npm run analyze' for bundle analysis.
- Compiles GenomeFeatureView to reduce bundle size.
- Ensure that esprima.js is not included in bundle by using a NOP.js file.
- Fix image reference for Tomasz on Team page.
- Bump version to 0.0.2 (mostly to ensure that I can detect the version. Going to automate this versioning in the future).
> Publish via Jenkins to alpha.m.org. Add bundle analyze. Reduce bundle size. 

- .eslintrc.js
- package-lock.json
- package.json
- src/api/BioLink.js
- src/components/LocalNav.vue
- src/components/MonarchAutocomplete.vue
- src/components/PhenotypesTable.vue
- src/main.js
- src/views/AnalyzePhenotypes.vue
- src/views/Node.vue
- tests/e2e/specs/disease.js
- tests/unit/About.spec.js
- tests/unit/test-utils.js
0.0.7
- Add another e2e test.
- Use BL 'development' which has the new shiny singular get_association_counts, as well as some other fixes.
- REALLY parallelize the BL calls to /graph and /bioentity. 0.0.6   prepped for this.
- Simplify Node.vue by eliminating the progress timer, which appears to   have been obviated over time.
- Eliminate the unnecessary has_gene_track state var in Node.vue.
- Simplify getNodeSummary, which doesn't need uri for LocalNav.vue (although really, all /bioentity funcs should return uri if possible.
- Calling the /identifier/prefixes/expand endpoint is stupid).
- Fixes many bugs in AnalyzePhenotypes.vue and LocalNav.vue.
- Improves layout of AP slightly
- Improves example used for debugging
- Fix some ESLint errors
- Change default for 'npm run lint' to …
> 0.0.7 - AnalyzePhenotypes fixes. ESLint changes. Code cleanup. Faster page load. Error handling.

- src/views/Sources.vue
Sources pages has two footers at the bottom:
https://beta.monarchinitiative.org/sources
> removed redundant footer in sources

- src/api/BioLink.js
- src/views/Sources.vue
to address https://github.com/monarch-initiative/monarch-ui/issues/58, slightly hacky injection of data about sources until we get these data from the API
@kshefchek @deepakunni3 have a look, I think this looks slightly better than the current source page. When we can pull these data from the API
`data.sourceDisplayName`
`data.ttlUrl`
`data.sourceVersion`
`data.monarchDataReleaseDate`
we can remove the hacktastic code I made below and things should work as normal. 
```
// remove this after we get this stuff from the API
for (var i = 0; i < bioentityResp.data.length; i++) {
var sourceDisplayName = bioentityResp.data[i].id.split(/[:.]+/)[1]
sourceDisplayName = sourceDisplayName.charAt(0).toUpperCase() + sourceDisplayName.slice(1);
bioentityResp.data[i].sourceDisplayName = sourceDisplayName …
```
> Temporary prettification of source page

- src/api/BioLink.js
Autocomplete changes
- If a user selects "gene", boost results based on connected edges
- If a user selects variant or genotype, use a minimal tokenizer
- down weight variants
- remove params that are not part of the rest call (interesting that an error is not returned)
- Set [minimum should match](https://lucene.apache.org/solr/guide/6_6/the-dismax-query-parser.html#TheDisMaxQueryParser-Themm_MinimumShouldMatch_Parameter) param to 67%
Search changes
- down weight variants
- Set [minimum should match](https://lucene.apache.org/solr/guide/6_6/the-dismax-query-parser.html#TheDisMaxQueryParser-Themm_MinimumShouldMatch_Parameter) param to 67%
See https://kshefchek.github.io/monarch-ui/
> Improvements to search and autocomplete

- src/api/BBOPGraphUtil.js
- src/api/StaticSourceData.js
- src/components/Navbar.vue
- Manually set ingest dates for ClinVar (no metadata yet for this ingest) and UDP (ingest hasn't been run in a while, so no up-to-date metadata)
- Also remove GeneReviews, since it isn't loaded currently
- Linting
> Manually set ingest dates for ClinVar and UDP on data sources page

- src/components/Navbar.vue
- src/router.js
- src/views/AboutLicensing.md
Trying to make some progress on (and heaven forfend, actual close!) [this ticket](https://github.com/monarch-initiative/monarch-ui/issues/186) - I made this PR, which basically turns Google Doc with an AboutLicensing page:
https://docs.google.com/document/d/1xeD2NEZvzVQrn16-oDwodqxVZV04OVX63Ch5yXWQ41s/edit#
Into this actual Monarch-UI page:
https://justaddcoffee.github.io/monarch-ui/about/licensing
@jmcmurry @monicacecilia have a look
Does anyone have licensing info for the monarch-ui itself? Can't find this info anywhere. Also, on that page, there are a few "Unknown License" items that you guys might have info about?
> Make about licensing page

- LICENSE.txt
Copying over the license from the legacy app repo
closes https://github.com/monarch-initiative/monarch-ui/issues/268
> Copy license from monarch-app

- src/api/BBOPGraphUtil.js
- src/views/Sources.vue
`schemaorg:logo` changed to `schema:logo`
> Fix predicate to retrieve logo URL from metadata

- src/components/Navbar.vue
- src/views/Licensing.vue
Make menu item for Ontologies that links to section in about/license that describes MI ontologies (per Moni's request here #296)
> Make menu item for Ontologies

- package.json
- src/api/BioLink.js
- src/components/AssocTable.vue
- src/components/PhenoGrid.vue
- src/components/PhenotypesTable.vue
- src/views/AnalyzePhenotypes.vue
- src/views/Node.vue
- Bumps phenogrid to test branch 1.5.1 which includes small fixes
- Replaces noncausal (genes|diseases) with correlated
- add unselect_evidence=true for biolink calls since this is no longer needed
- Support fragment formatted identifiers (eg HP_1234) after reviewing IMPC phenogrid
fixes #283
> phenogrid fixes, change noncausal to correlated

- src/api/MyGene.js
Fixes the bad link to JBrowse; also adds the default track to the JBrowse URL parameters so that at least one view of the tracks will be displayed
> fixes #346, broken JBrowse link

- .browserslistrc
changes to browserslistrc conf:
```>1%``` changed to ```>.10%```
```not ie <= 8``` to changed to ```not ie <= 11```
```last 2 versions``` removed
closes #365
> update browserslistrc to support more browsers

- src/views/Licensing.vue
Fixes broken reusable data link on https://monarchinitiative.org/about/licensing
> fix reusable data org link

- package-lock.json
- src/views/Node.vue
I noticed that the GARD link for MONDO:0018484 was pointing to 
https://rarediseases.info.nih.gov/diseases/1993/semicircular-canal-dehiscence-syndrome
rather than 
https://rarediseases.info.nih.gov/diseases/10993/semicircular-canal-dehiscence-syndrome
I was going to just create an issue, but it was such an odd error that I went looking for it on my own. It made a lot more sense once I saw the necessary ID->url conversion.
> only remove leading zeroes when building GARD URLs

- src/views/Search.vue
variant and genotype labels are not showing their superscripted parts in our search view, this PR fixes this
for example, on https://monarchinitiative.org/search/SHH filter on variants
> fix variant and genotype labels in our search view

- src/main.js
I'm currently seeing the warning:
> Cookie “_ga” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite
adding this cookie_flag should fix this
> add SameSite header to gtag

- src/lib/CategoryMap.js
- src/views/TextAnnotator.vue
Addresses #209. Removes unlinked recognized terms; adds ability to download all results; adds info popup text to 'Download' and 'Analyze Phenotypes' buttons.
> Enhancements to text annotator

- src/api/BioLink.js
- src/components/Navbar.vue
- adds flag `?api=google-cloud` to enable testing of the new google cloud services. this should only be temporary while we migrate over to google cloud.
- changes the wording of the beta warning a bit
> Add flag to test out new google cloud versions of apis

- src/api/BioLink.js
Came across errors when i tried to do `?api=google-cloud` on the live site, but the pr that added that particular flag hadn't went live yet. This makes it so if user types in not supported flag, like `?api=tomatoes`, it defaults to production.
> avoid errors when api flag value not found, change gc comment

- package-lock.json
- package.json
- src/components/PhenoGrid.vue
- src/main.js
closes #443 
@falquaddoomi fixed the upstream `phenogrid` issues in https://github.com/monarch-initiative/phenogrid/pull/282 . This updates the version of the `phenogrid` package being used and fixes the import. After the Monarch folks have tested this out in the deploy preview below, we can merge the `phenogrid` pr, publish the new version to npm, change this pr to install from npm (instead of the hacky install from @falquaddoomi 's github repo), then merge this.
> Phenogrid fix

- .github/workflows/deploy-production.yaml
- .github/workflows/deploy.yaml
Move production to GitHub Pages to address and close #456 . GitHub Pages doesn't seem to have the same problems as Netlify in China.
After merge, the controller of the monarch domain just needs to [follow these steps](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#configuring-an-apex-domain) to make the domain point to GitHub Pages instead of Netlify.
> add workflow to deploy prod to gh-pages

- README.md
- src/api/bio-link.js
In anticipation of Kent leaving the team, we would like to start more seriously testing the new Google Cloud instance of the API (and other services) with the live web app. This PR switches the production/beta/etc flag on the frontend to use the Google Cloud version by default. Eventually, and soon, we'll want to switch the DNS configuration so that `https://api.monarchinitiative.org/api/` actually points to the Google Cloud instance, and not the instance still running on Oregon State University hardware. Faisal, let me know when you want to make that switch.
> switch to google cloud version of api for production

- package-lock.json
- package.json
- src/components/PhenoGrid.vue
The phenogrid component checks if the backend API matches a fixed set of hostnames to determine if it's a biolink API or not. Unfortunately, this breaks the component while we're using a non-standard backend API URL.
This PR updates phenogrid to 1.5.3, which adds the `forceBiolink` flag to phenogrid's constructor. `PhenoGrid.vue` sets it to true, so that the component always works against the biolink API regardless of the backend API URL.
> Works around phenogrid's biolink backend sniffing
